version: '3.3'

services:

  mqtt-server:
    build:
      context: ./mqtt_docker
      dockerfile: Dockerfile
#    volumes:
#      - ./.docker/mosquitto/mosquitto_conf:/mosquitto/config
#      - ./.docker/mosquitto/mosquitto_data:/mosquitto/data
#      - ./.docker/mosquitto/mosquitto_log:/mosquitto/log
    environment:
      - MOSQUITTO_USERNAME=username
      - MOSQUITTO_PASSWORD=password
    container_name: eclipse-mosquitto
    restart: always
    ports:
      - 9001:9001
      - 1883:1883

#  mqtt-ui:
#    image: hivemq/hivemq4
##    build:
##      context: ./mqtt_explorer
##      dockerfile: Dockerfile
#    #    volumes:
#    #      - ./.docker/mosquitto/mosquitto_conf:/mosquitto/config
#    #      - ./.docker/mosquitto/mosquitto_data:/mosquitto/data
#    #      - ./.docker/mosquitto/mosquitto_log:/mosquitto/log
#    container_name: HiveMQ
#    restart: always
#    ports:
#      - 1883:1883
#      - 8080:8080

  sqs-queue:
    container_name: sqs-queue
    build:
      context: ./sqs_docker
      dockerfile: Dockerfile
    ports:
      - "9324:9324"
      - "9325:9325"
    stdin_open: true
    tty: true
#    volume:
#      - "./.docker/volumes/sqs_queue/opt/alpine-sqs:/opt/custom"

  sqs-producer-app:
    container_name: sqs-producer-app
    build:
      context: ./sqs_producer
      dockerfile: Dockerfile
    ports:
      - '8081:8080'

  sqs-consumer-app:
    container_name: sqs-consumer-app
    build:
      context: ./sqs_consumer
      dockerfile: Dockerfile
    ports:
      - '8082:8080'