application:
  developer: Nizami Islamovs
  version: v 1.0.0
  deploymentdate: 2018-09-11 21:15:29
  support.email: nizamiislamovs@gmail.com
  description: SQS consumer mcs
  title: SQS consumer mcs

management:
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"
      cors:
        allowed-methods: GET, POST, PUT, DELETE, OPTIONS
        max-age: 3600s
        #        allowed-origins: '*'
        allow-credentials: true

cloud:
  aws:
    region:
      static: eu-central-1
      auto: false
    credentials:
      access-key: notValidKey
      secret-key: notValidSecret
    end-point:
      uri: http://sqs-queue:9324/queue/mqtt_queue


mqtt-properties:
  host: tcp://mqtt-server:1883
  clientId: Server
  username: mosquitto
  password:
  cleanSession: false
  connectionTimeout: 300
  keepAliveInterval: 60
  # If this property is set to true, the connection will be automatically reconnected when disconnected
  automaticReconnect: true