application:
  developer: Nizami Islamovs
  version: v 1.0.0
  deploymentdate: 2018-09-11 21:15:29
  support.email: nizamiislamovs@gmail.com
  description: SQS consumer mcs
  title: SQS consumer mcs

management:
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"
      cors:
        allowed-methods: GET, POST, PUT, DELETE, OPTIONS
        max-age: 3600s
        #        allowed-origins: '*'
        allow-credentials: true

cloud:
  aws:
    region:
      static: eu-central-1
      auto: false
    credentials:
      access-key: notValidKey
      secret-key: notValidSecret
    end-point:
      uri: http://sqs-queue:9324/queue/mqtt_queue

mqtt:
  automaticReconnect: true
  cleanSession: true
  connectionTimeout: 10
  #clientId: ${COMPUTERNAME}-MQTT
  clientId: TEST-MQTT
  host: tcp://mqtt-server:1883